classDiagram
    class ConsoleLogger {

        -iterations : int
        -strategy : LoggingStrategy
        -instance : Logger$

        -Logger()
        -log(string) void
        -get_timestamp()
        +get_instance() Logger&$
    }

class LoggingStrategy {
        <<abstract>>

        +log(string) void*
    }

    ConsoleLogger --> LoggingStrategy