classDiagram
    class Logger {

        -iterations : int
        -instance : Logger$


        -Logger()
        -get_clock() int
        -is_prime() bool
        +date_time_test() void
        +get_instance() Logger&$
    }